name: Build and Release Go Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    container:
      image: golang:1.23
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get update && apt-get install -y libgl1-mesa-dev xorg-dev libxcursor-dev

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/myapp-linux-amd64 ./cmd/main.go

      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: dist/myapp-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build for Windows
    runs-on: ubuntu-latest
    container:
      image: tianon/golang-cross  # imagem com toolchain mingw
    steps:
      - uses: actions/checkout@v4

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=windows GOARCH=amd64 go build -o dist/myapp-windows-amd64.exe ./cmd/main.go

      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: dist/myapp-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=darwin GOARCH=amd64 go build -o dist/myapp-darwin-amd64 ./cmd/main.go

      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: dist/myapp-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}