name: Build Go Binaries

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Instalar dependências
        run: go mod tidy

      - name: Compilar binário
        run: |
          GOOS=$(go env GOOS)
          GOARCH=$(go env GOARCH)
          EXT=""
          if [[ "$GOOS" == "windows" ]]; then EXT=".exe"; fi
          go build -o build/meu_programa-$GOOS-$GOARCH$EXT

      - name: Upload binário compilado
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: build/
